---
name: Lint Code Base

'on':
  push:
  workflow_call:

permissions:
  actions: none
  checks: none              # add custom pass/fail checks to the PR
  contents: read            # git permissions to repo pull/push
  deployments: none
  issues: none              # read/write to repo Issues
  packages: none            # read/write to repo Packages (ghcr, gems, npm)
  pull-requests: none       # read/write to repo PRs
  repository-projects: none
  security-events: none     # read/write to repo Security tab API
  statuses: write           # read/write to repo custom statuses and checks

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set DEFAULT_BRANCH to PR target
        if: ${{ github.base_ref != '' }}
        run: |
          # shellcheck disable=2086
          echo "DEFAULT_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
          echo "this is a PR branch. only lint files that are changed"

      - name: Set DEFAULT_BRANCH to current branch
        if: ${{ github.base_ref == '' }}
        run: |
          # shellcheck disable=2086
          echo "DEFAULT_BRANCH=$(echo '${{ github.ref }}' |
          sed 's/refs\/heads\///')" >> $GITHUB_ENV
          echo "this is just a branch push, not a PR."

      - name: Are we linting all files?
        run: |
          echo VALIDATE_ALL_CODEBASE=
          ${{ !contains(github.event_name, 'pull_request') }}

      - name: Lint Code Base
        uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}
          VALIDATE_ALL_CODEBASE:
            ${{ !contains(github.event_name, 'pull_request') }}
          VALIDATE_DOCKERFILE: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_JSCPD: false
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas
