name: Security Checks

on:
  push:
    paths-ignore: 
      - "README.md"
      - ".github/**"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_call:

permissions:
  actions: none
  checks:  none             #add custom pass/fail checks to the PR
  contents: read            #git permissions to repo pull/push
  deployments: none
  issues: write              #read/write to repo Issues
  packages: none            #read/write to repo Packages (ghcr, gems, npm)
  pull-requests: write       #read/write to repo PRs
  repository-projects: none
  security-events: none     #read/write to repo Security tab API
  statuses: write           #read/write to repo custom statuses and checks

jobs:
  scan:
    name: Setup  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [ latest ]
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          
      - name: Login to DockerHub
         uses: docker/login-action@v1 
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}    
        
       - name: Pull docker image
         run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag }}
        
       - name: Trivy
         uses: homoluctus/gitrivy@v2  
         with:
           issue: false
           image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag }}
           token: ${{ secrets.GITHUB_TOKEN }}
            
       - name: Snyk
         uses: snyk/actions/docker@master
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag }}
           args: --severity-threshold=high
           
