name: Security Checks

on:
  push:
    paths-ignore: 
      - "README.md"
      - ".github/**"
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_call:

permissions:
  actions: none
  checks:  none             #add custom pass/fail checks to the PR
  contents: read            #git permissions to repo pull/push
  deployments: none
  issues: write              #read/write to repo Issues
  packages: none            #read/write to repo Packages (ghcr, gems, npm)
  pull-requests: write       #read/write to repo PRs
  repository-projects: none
  security-events: none     #read/write to repo Security tab API
  statuses: write           #read/write to repo custom statuses and checks

jobs:
  scan:
    name: Setup  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest,22.2.0,22.1.1,21.0.4,21.0.3,21.0.2,21.0.1,21.0.0,20.0.12,20.0.9,20.0.8,20.0.7,20.0.6,20.0.5,20.0.4,20.0.3,20.0.2,20.0.1,20.0.0,19.0.10,19.0.9,19.0.8,19.0.7,19.0.6,19.0.5,19.0.4,19.0.3,19.0.2,19.0.1,19.0.0,18.0.6,18.0.5,18.0.4,18.0.3,18.0.1,17.0.3]
    steps:    
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          
      - name: Login to DockerHub
         uses: docker/login-action@v1 
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}    
        
       - name: Pull docker image
         run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag }}
        
       - name: Trivy
         uses: homoluctus/gitrivy@v2  
         with:
           issue: false
           image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag }}
           token: ${{ secrets.GITHUB_TOKEN }}
            
       - name: Snyk
         uses: snyk/actions/docker@master
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ matrix.tag }}
           args: --severity-threshold=high
           
